services:
  redis:
    image: redis:6-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  api:
    image: eclipse-temurin:23-jdk
    build: .
    ports:
      - "8080-8081:8080"
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2